# source existing zprofile file backed up if exists
if [ -f "$HOME/.bash_profile.backup" ]; then
    source "$HOME/.bash_profile.backup"
fi

source "$HOME/.profile"

# Local Variables:
# mode: bash-ts
# End:
