# source existing zprofile file backed up if exists
if [ -f "$HOME/.bashrc.backup" ]; then
    source "$HOME/.bashrc.backup"
fi

[[ "$INSIDE_EMACS" = 'ghostel' ]] && source ~/.local/share/ghostel/ghostel.bash

source "$HOME/.zshrc"

# Local Variables:
# mode: bash-ts
# End:
