if [ -n "$BASH_SOURCE" ]; then
    CURRENT_SCRIPT="$BASH_SOURCE"
elif [ -n "$ZSH_NAME" ]; then
    CURRENT_SCRIPT="${(%):-%N}"
else
    CURRENT_SCRIPT="$0"
fi

DOTFILES_ROOT=$(dirname $(dirname "$(readlink -f "$CURRENT_SCRIPT")"))

# source existing zprofile file backed up if exists
if [ -f "$HOME/.zprofile.backup" ]; then
    source "$HOME/.zprofile.backup"
fi

# If install according to the README, this will work
if [[ "$(uname)" == "Darwin" ]]; then
    export EDITOR="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -r -a ''"
else
    # we are in Linux
    export EDITOR="emacsclient -r -a ''"
fi

export JAVA_HOME=$DOTFILES_ROOT/.tools/java
export PATH=$DOTFILES_ROOT/.pixi/envs/all/bin:$JAVA_HOME/bin:$HOME/.local/bin:/bin:$PATH

# mac setting
if [[ "$(uname)" == "Darwin" ]]; then
  current_value=$(defaults read com.apple.dock show-recents 2>/dev/null)
  if [[ "$current_value" != "0" && "$current_value" != "false" ]]; then
    defaults write com.apple.dock show-recents -bool false
    killall Dock >/dev/null 2>&1
  fi
fi

# Local Variables:
# mode: bash-ts
# End:
