# source existing zprofile file backed up if exists
if [ -f "$HOME/.zprofile.backup" ]; then
    source "$HOME/.zprofile.backup"
fi

export EDITOR="emacsclient -r -a ''"

# mac setting
if [[ "$(uname)" == "Darwin" ]]; then
  current_value=$(defaults read com.apple.dock show-recents 2>/dev/null)
  if [[ "$current_value" != "0" && "$current_value" != "false" ]]; then
    defaults write com.apple.dock show-recents -bool false
    killall Dock >/dev/null 2>&1
  fi
fi

source $HOME/.profile

# Local Variables:
# mode: bash-ts
# End:
